name: CI - Databricks Bundle Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Databricks CLI
        run: pip install databricks-cli
      - name: Configure Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks configure --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN
      - name: Validate Bundle
        run: databricks bundle validate --target dev
      - name: Deploy Bundle
        run: databricks bundle deploy --target dev
